name: onlineretail
dependencies:
    - python>=3.7
    - pip
    - matplotlib
    - pandas
    - xlrd
    - pandas-profiling
    - numpy
    - seaborn
    - scikit-learn
    - scipy
    - jupyterlab
    - openpyxl
    - requests
    - zipfile
    - pip:
        - lifetimes